# H2 Database
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# Enable H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Allow H2 Console in browser
#spring.h2.console.settings.web-allow-others=true

spring.datasource.url=jdbc:postgresql://localhost:5432/sithappens
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

